<?php

namespace Database\Seeders;

use App\Models\Agent;
use App\Models\AgentSpecialities;
use App\Models\Contact;
use App\Models\Mission;
use App\Models\MissionInfo;
use App\Models\SafeHouse;
use App\Models\Target;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{


    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        //insert data into table country
        DB::table('countries')->delete();

        $countries = array(
            array('country_name' => 'United States'),
            array('country_name' => 'Canada'),
            array('country_name' => 'Afghanistan'),
            array('country_name' => 'Albania'),
            array('country_name' => 'Algeria'),
            array('country_name' => 'American Samoa'),
            array('country_name' => 'Andorra'),
            array('country_name' => 'Angola'),
            array('country_name' => 'Anguilla'),
            array('country_name' => 'Antarctica'),
            array('country_name' => 'Antigua and/or Barbuda'),
            array('country_name' => 'Argentina'),
            array('country_name' => 'Armenia'),
            array('country_name' => 'Aruba'),
            array('country_name' => 'Australia'),
            array('country_name' => 'Austria'),
            array('country_name' => 'Azerbaijan'),
            array('country_name' => 'Bahamas'),
            array('country_name' => 'Bahrain'),
            array('country_name' => 'Bangladesh'),
            array('country_name' => 'Barbados'),
            array('country_name' => 'Belarus'),
            array('country_name' => 'Belgium'),
            array('country_name' => 'Belize'),
            array('country_name' => 'Benin'),
            array('country_name' => 'Bermuda'),
            array('country_name' => 'Bhutan'),
            array('country_name' => 'Bolivia'),
            array('country_name' => 'Bosnia and Herzegovina'),
            array('country_name' => 'Botswana'),
            array('country_name' => 'Bouvet Island'),
            array('country_name' => 'Brazil'),
            array('country_name' => 'British lndian Ocean Territory'),
            array('country_name' => 'Brunei Darussalam'),
            array('country_name' => 'Bulgaria'),
            array('country_name' => 'Burkina Faso'),
            array('country_name' => 'Burundi'),
            array('country_name' => 'Cambodia'),
            array('country_name' => 'Cameroon'),
            array('country_name' => 'Cape Verde'),
            array('country_name' => 'Cayman Islands'),
            array('country_name' => 'Central African Republic'),
            array('country_name' => 'Chad'),
            array('country_name' => 'Chile'),
            array('country_name' => 'China'),
            array('country_name' => 'Christmas Island'),
            array('country_name' => 'Cocos (Keeling) Islands'),
            array('country_name' => 'Colombia'),
            array('country_name' => 'Comoros'),
            array('country_name' => 'Congo'),
            array('country_name' => 'Cook Islands'),
            array('country_name' => 'Costa Rica'),
            array('country_name' => 'Croatia (Hrvatska)'),
            array('country_name' => 'Cuba'),
            array('country_name' => 'Cyprus'),
            array('country_name' => 'Czech Republic'),
            array('country_name' => 'Democratic Republic of Congo'),
            array('country_name' => 'Denmark'),
            array('country_name' => 'Djibouti'),
            array('country_name' => 'Dominica'),
            array('country_name' => 'Dominican Republic'),
            array('country_name' => 'East Timor'),
            array('country_name' => 'Ecudaor'),
            array('country_name' => 'Egypt'),
            array('country_name' => 'El Salvador'),
            array('country_name' => 'Equatorial Guinea'),
            array('country_name' => 'Eritrea'),
            array('country_name' => 'Estonia'),
            array('country_name' => 'Ethiopia'),
            array('country_name' => 'Falkland Islands (Malvinas)'),
            array('country_name' => 'Faroe Islands'),
            array('country_name' => 'Fiji'),
            array('country_name' => 'Finland'),
            array('country_name' => 'France'),
            array('country_name' => 'France, Metropolitan'),
            array('country_name' => 'French Guiana'),
            array('country_name' => 'French Polynesia'),
            array('country_name' => 'French Southern Territories'),
            array('country_name' => 'Gabon'),
            array('country_name' => 'Gambia'),
            array('country_name' => 'Georgia'),
            array('country_name' => 'Germany'),
            array('country_name' => 'Ghana'),
            array('country_name' => 'Gibraltar'),
            array('country_name' => 'Greece'),
            array('country_name' => 'Greenland'),
            array('country_name' => 'Grenada'),
            array('country_name' => 'Guadeloupe'),
            array('country_name' => 'Guam'),
            array('country_name' => 'Guatemala'),
            array('country_name' => 'Guinea'),
            array('country_name' => 'Guinea-Bissau'),
            array('country_name' => 'Guyana'),
            array('country_name' => 'Haiti'),
            array('country_name' => 'Heard and Mc Donald Islands'),
            array('country_name' => 'Honduras'),
            array('country_name' => 'Hong Kong'),
            array('country_name' => 'Hungary'),
            array('country_name' => 'Iceland'),
            array('country_name' => 'India'),
            array('country_name' => 'Indonesia'),
            array('country_name' => 'Iran (Islamic Republic of)'),
            array('country_name' => 'Iraq'),
            array('country_name' => 'Ireland'),
            array('country_name' => 'Israel'),
            array('country_name' => 'Italy'),
            array('country_name' => 'Ivory Coast'),
            array('country_name' => 'Jamaica'),
            array('country_name' => 'Japan'),
            array('country_name' => 'Jordan'),
            array('country_name' => 'Kazakhstan'),
            array('country_name' => 'Kenya'),
            array('country_name' => 'Kiribati'),
            array('country_name' => 'Korea, Democratic People\'s Republic of'),
            array('country_name' => 'Korea, Republic of'),
            array('country_name' => 'Kuwait'),
            array('country_name' => 'Kyrgyzstan'),
            array('country_name' => 'Lao People\'s Democratic Republic'),
            array('country_name' => 'Latvia'),
            array('country_name' => 'Lebanon'),
            array('country_name' => 'Lesotho'),
            array('country_name' => 'Liberia'),
            array('country_name' => 'Libyan Arab Jamahiriya'),
            array('country_name' => 'Liechtenstein'),
            array('country_name' => 'Lithuania'),
            array('country_name' => 'Luxembourg'),
            array('country_name' => 'Macau'),
            array('country_name' => 'Macedonia'),
            array('country_name' => 'Madagascar'),
            array('country_name' => 'Malawi'),
            array('country_name' => 'Malaysia'),
            array('country_name' => 'Maldives'),
            array('country_name' => 'Mali'),
            array('country_name' => 'Malta'),
            array('country_name' => 'Marshall Islands'),
            array('country_name' => 'Martinique'),
            array('country_name' => 'Mauritania'),
            array('country_name' => 'Mauritius'),
            array('country_name' => 'Mayotte'),
            array('country_name' => 'Mexico'),
            array('country_name' => 'Micronesia, Federated States of'),
            array('country_name' => 'Moldova, Republic of'),
            array('country_name' => 'Monaco'),
            array('country_name' => 'Mongolia'),
            array('country_name' => 'Montserrat'),
            array('country_name' => 'Morocco'),
            array('country_name' => 'Mozambique'),
            array('country_name' => 'Myanmar'),
            array('country_name' => 'Namibia'),
            array('country_name' => 'Nauru'),
            array('country_name' => 'Nepal'),
            array('country_name' => 'Netherlands'),
            array('country_name' => 'Netherlands Antilles'),
            array('country_name' => 'New Caledonia'),
            array('country_name' => 'New Zealand'),
            array('country_name' => 'Nicaragua'),
            array('country_name' => 'Niger'),
            array('country_name' => 'Nigeria'),
            array('country_name' => 'Niue'),
            array('country_name' => 'Norfork Island'),
            array('country_name' => 'Northern Mariana Islands'),
            array('country_name' => 'Norway'),
            array('country_name' => 'Oman'),
            array('country_name' => 'Pakistan'),
            array('country_name' => 'Palau'),
            array('country_name' => 'Panama'),
            array('country_name' => 'Papua New Guinea'),
            array('country_name' => 'Paraguay'),
            array('country_name' => 'Peru'),
            array('country_name' => 'Philippines'),
            array('country_name' => 'Pitcairn'),
            array('country_name' => 'Poland'),
            array('country_name' => 'Portugal'),
            array('country_name' => 'Puerto Rico'),
            array('country_name' => 'Qatar'),
            array('country_name' => 'Republic of South Sudan'),
            array('country_name' => 'Reunion'),
            array('country_name' => 'Romania'),
            array('country_name' => 'Russian Federation'),
            array('country_name' => 'Rwanda'),
            array('country_name' => 'Saint Kitts and Nevis'),
            array('country_name' => 'Saint Lucia'),
            array('country_name' => 'Saint Vincent and the Grenadines'),
            array('country_name' => 'Samoa'),
            array('country_name' => 'San Marino'),
            array('country_name' => 'Sao Tome and Principe'),
            array('country_name' => 'Saudi Arabia'),
            array('country_name' => 'Senegal'),
            array('country_name' => 'Serbia'),
            array('country_name' => 'Seychelles'),
            array('country_name' => 'Sierra Leone'),
            array('country_name' => 'Singapore'),
            array('country_name' => 'Slovakia'),
            array('country_name' => 'Slovenia'),
            array('country_name' => 'Solomon Islands'),
            array('country_name' => 'Somalia'),
            array('country_name' => 'South Africa'),
            array('country_name' => 'South Georgia South Sandwich Islands'),
            array('country_name' => 'Spain'),
            array('country_name' => 'Sri Lanka'),
            array('country_name' => 'St. Helena'),
            array('country_name' => 'St. Pierre and Miquelon'),
            array('country_name' => 'Sudan'),
            array('country_name' => 'Suricountry_name'),
            array('country_name' => 'Svalbarn and Jan Mayen Islands'),
            array('country_name' => 'Swaziland'),
            array('country_name' => 'Sweden'),
            array('country_name' => 'Switzerland'),
            array('country_name' => 'Syrian Arab Republic'),
            array('country_name' => 'Taiwan'),
            array('country_name' => 'Tajikistan'),
            array('country_name' => 'Tanzania, United Republic of'),
            array('country_name' => 'Thailand'),
            array('country_name' => 'Togo'),
            array('country_name' => 'Tokelau'),
            array('country_name' => 'Tonga'),
            array('country_name' => 'Trinidad and Tobago'),
            array('country_name' => 'Tunisia'),
            array('country_name' => 'Turkey'),
            array('country_name' => 'Turkmenistan'),
            array('country_name' => 'Turks and Caicos Islands'),
            array('country_name' => 'Tuvalu'),
            array('country_name' => 'Uganda'),
            array('country_name' => 'Ukraine'),
            array('country_name' => 'United Arab Emirates'),
            array('country_name' => 'United Kingdom'),
            array('country_name' => 'United States minor outlying islands'),
            array('country_name' => 'Uruguay'),
            array('country_name' => 'Uzbekistan'),
            array('country_name' => 'Vanuatu'),
            array('country_name' => 'Vatican City State'),
            array('country_name' => 'Venezuela'),
            array('country_name' => 'Vietnam'),
            array('country_name' => 'Virgin Islands (British)'),
            array('country_name' => 'Virgin Islands (U.S.)'),
            array('country_name' => 'Wallis and Futuna Islands'),
            array('country_name' => 'Western Sahara'),
            array('country_name' => 'Yemen'),
            array('country_name' => 'Yugoslavia'),
            array('country_name' => 'Zaire'),
            array('country_name' => 'Zambia'),
            array('country_name' => 'Zimbabwe'),
        );

        DB::table('countries')->insert($countries);

        // insert data into table nationalities
        DB::table('nationalities')->delete();

        $nationals = array(

            array('nationality_name' => 'Afghan'),
            array('nationality_name' => 'Albanian'),
            array('nationality_name' => 'Algerian'),
            array('nationality_name' => 'American'),
            array('nationality_name' => 'Andorran'),
            array('nationality_name' => 'Angolan'),
            array('nationality_name' => 'Antiguans'),
            array('nationality_name' => 'Argentinean'),
            array('nationality_name' => 'Armenian'),
            array('nationality_name' => 'Australian'),
            array('nationality_name' => 'Austrian'),
            array('nationality_name' => 'Azerbaijani'),
            array('nationality_name' => 'Bahamian'),
            array('nationality_name' => 'Bahraini'),
            array('nationality_name' => 'Bangladeshi'),
            array('nationality_name' => 'Barbadian'),
            array('nationality_name' => 'Barbudans'),
            array('nationality_name' => 'Batswana'),
            array('nationality_name' => 'Belarusian'),
            array('nationality_name' => 'Belgian'),
            array('nationality_name' => 'Belizean'),
            array('nationality_name' => 'Beninese'),
            array('nationality_name' => 'Bhutanese'),
            array('nationality_name' => 'Bolivian'),
            array('nationality_name' => 'Bosnian'),
            array('nationality_name' => 'Brazilian'),
            array('nationality_name' => 'British'),
            array('nationality_name' => 'Bruneian'),
            array('nationality_name' => 'Bulgarian'),
            array('nationality_name' => 'Burkinabe'),
            array('nationality_name' => 'Burmese'),
            array('nationality_name' => 'Burundian'),
            array('nationality_name' => 'Cambodian'),
            array('nationality_name' => 'Cameroonian'),
            array('nationality_name' => 'Canadian'),
            array('nationality_name' => 'Cape Verdean'),
            array('nationality_name' => 'Central African'),
            array('nationality_name' => 'Chadian'),
            array('nationality_name' => 'Chilean'),
            array('nationality_name' => 'Chinese'),
            array('nationality_name' => 'Colombian'),
            array('nationality_name' => 'Comoran'),
            array('nationality_name' => 'Congolese'),
            array('nationality_name' => 'Costa Rican'),
            array('nationality_name' => 'Croatian'),
            array('nationality_name' => 'Cuban'),
            array('nationality_name' => 'Cypriot'),
            array('nationality_name' => 'Czech'),
            array('nationality_name' => 'Danish'),
            array('nationality_name' => 'Djibouti'),
            array('nationality_name' => 'Dominican'),
            array('nationality_name' => 'Dutch'),
            array('nationality_name' => 'East Timorese'),
            array('nationality_name' => 'Ecuadorean'),
            array('nationality_name' => 'Egyptian'),
            array('nationality_name' => 'Emirian'),
            array('nationality_name' => 'Equatorial Guinean'),
            array('nationality_name' => 'Eritrean'),
            array('nationality_name' => 'Estonian'),
            array('nationality_name' => 'Ethiopian'),
            array('nationality_name' => 'Fijian'),
            array('nationality_name' => 'Filipino'),
            array('nationality_name' => 'Finnish'),
            array('nationality_name' => 'French'),
            array('nationality_name' => 'Gabonese'),
            array('nationality_name' => 'Gambian'),
            array('nationality_name' => 'Georgian'),
            array('nationality_name' => 'German'),
            array('nationality_name' => 'Ghanaian'),
            array('nationality_name' => 'Greek'),
            array('nationality_name' => 'Grenadian'),
            array('nationality_name' => 'Guatemalan'),
            array('nationality_name' => 'Guinea-Bissauan'),
            array('nationality_name' => 'Guinean'),
            array('nationality_name' => 'Guyanese'),
            array('nationality_name' => 'Haitian'),
            array('nationality_name' => 'Herzegovinian'),
            array('nationality_name' => 'Honduran'),
            array('nationality_name' => 'Hungarian'),
            array('nationality_name' => 'I-Kiribati'),
            array('nationality_name' => 'Icelander'),
            array('nationality_name' => 'Indian'),
            array('nationality_name' => 'Indonesian'),
            array('nationality_name' => 'Iranian'),
            array('nationality_name' => 'Iraqi'),
            array('nationality_name' => 'Irish'),
            array('nationality_name' => 'Israeli'),
            array('nationality_name' => 'Italian'),
            array('nationality_name' => 'Ivorian'),
            array('nationality_name' => 'Jamaican'),
            array('nationality_name' => 'Japanese'),
            array('nationality_name' => 'Jordanian'),
            array('nationality_name' => 'Kazakhstani'),
            array('nationality_name' => 'Kenyan'),
            array('nationality_name' => 'Kittian and Nevisian'),
            array('nationality_name' => 'Kuwaiti'),
            array('nationality_name' => 'Kyrgyz'),
            array('nationality_name' => 'Laotian'),
            array('nationality_name' => 'Latvian'),
            array('nationality_name' => 'Lebanese'),
            array('nationality_name' => 'Liberian'),
            array('nationality_name' => 'Libyan'),
            array('nationality_name' => 'Liechtensteiner'),
            array('nationality_name' => 'Lithuanian'),
            array('nationality_name' => 'Luxembourger'),
            array('nationality_name' => 'Macedonian'),
            array('nationality_name' => 'Malagasy'),
            array('nationality_name' => 'Malawian'),
            array('nationality_name' => 'Malaysian'),
            array('nationality_name' => 'Maldivan'),
            array('nationality_name' => 'Malian'),
            array('nationality_name' => 'Maltese'),
            array('nationality_name' => 'Marshallese'),
            array('nationality_name' => 'Mauritanian'),
            array('nationality_name' => 'Mauritian'),
            array('nationality_name' => 'Mexican'),
            array('nationality_name' => 'Micronesian'),
            array('nationality_name' => 'Moldovan'),
            array('nationality_name' => 'Monacan'),
            array('nationality_name' => 'Mongolian'),
            array('nationality_name' => 'Moroccan'),
            array('nationality_name' => 'Mosotho'),
            array('nationality_name' => 'Motswana'),
            array('nationality_name' => 'Mozambican'),
            array('nationality_name' => 'Namibian'),
            array('nationality_name' => 'Nauruan'),
            array('nationality_name' => 'Nepalese'),
            array('nationality_name' => 'New Zealander'),
            array('nationality_name' => 'Nicaraguan'),
            array('nationality_name' => 'Nigerian'),
            array('nationality_name' => 'Nigerien'),
            array('nationality_name' => 'North Korean'),
            array('nationality_name' => 'Northern Irish'),
            array('nationality_name' => 'Norwegian'),
            array('nationality_name' => 'Omani'),
            array('nationality_name' => 'Pakistani'),
            array('nationality_name' => 'Palauan'),
            array('nationality_name' => 'Panamanian'),
            array('nationality_name' => 'Papua New Guinean'),
            array('nationality_name' => 'Paraguayan'),
            array('nationality_name' => 'Peruvian'),
            array('nationality_name' => 'Polish'),
            array('nationality_name' => 'Portuguese'),
            array('nationality_name' => 'Qatari'),
            array('nationality_name' => 'Romanian'),
            array('nationality_name' => 'Russian'),
            array('nationality_name' => 'Rwandan'),
            array('nationality_name' => 'Saint Lucian'),
            array('nationality_name' => 'Salvadoran'),
            array('nationality_name' => 'Samoan'),
            array('nationality_name' => 'San Marinese'),
            array('nationality_name' => 'Sao Tomean'),
            array('nationality_name' => 'Saudi'),
            array('nationality_name' => 'Scottish'),
            array('nationality_name' => 'Senegalese'),
            array('nationality_name' => 'Serbian'),
            array('nationality_name' => 'Seychellois'),
            array('nationality_name' => 'Sierra Leonean'),
            array('nationality_name' => 'Singaporean'),
            array('nationality_name' => 'Slovakian'),
            array('nationality_name' => 'Slovenian'),
            array('nationality_name' => 'Solomon Islander'),
            array('nationality_name' => 'Somali'),
            array('nationality_name' => 'South African'),
            array('nationality_name' => 'South Korean'),
            array('nationality_name' => 'Spanish'),
            array('nationality_name' => 'Sri Lankan'),
            array('nationality_name' => 'Sudanese'),
            array('nationality_name' => 'Surinamer'),
            array('nationality_name' => 'Swazi'),
            array('nationality_name' => 'Swedish'),
            array('nationality_name' => 'Swiss'),
            array('nationality_name' => 'Syrian'),
            array('nationality_name' => 'Taiwanese'),
            array('nationality_name' => 'Tajik'),
            array('nationality_name' => 'Tanzanian'),
            array('nationality_name' => 'Thai'),
            array('nationality_name' => 'Togolese'),
            array('nationality_name' => 'Tongan'),
            array('nationality_name' => 'Trinidadian/Tobagonian'),
            array('nationality_name' => 'Tunisian'),
            array('nationality_name' => 'Turkish'),
            array('nationality_name' => 'Tuvaluan'),
            array('nationality_name' => 'Ugandan'),
            array('nationality_name' => 'Ukrainian'),
            array('nationality_name' => 'Uruguayan'),
            array('nationality_name' => 'Uzbekistani'),
            array('nationality_name' => 'Venezuelan'),
            array('nationality_name' => 'Vietnamese'),
            array('nationality_name' => 'Welsh'),
            array('nationality_name' => 'Yemenite'),
            array('nationality_name' => 'Zambian'),
            array('nationality_name' => 'Zimbabwean')
        );

        DB::table('nationalities')->insert($nationals);

        // insert data for table specialities
        DB::table('specialities')->delete();
        $specialities = array(
            array('speciality_name' => 'tireur d\'élite'),
            array('speciality_name' => 'pose de micro'),
            array('speciality_name' => 'démolition'),
            array('speciality_name' => 'ouverture de porte'),
            array('speciality_name' => 'filature'),
            array('speciality_name' => 'escorte'),
            array('speciality_name' => 'exfiltration'),
            array('speciality_name' => 'infiltration'),
            array('speciality_name' => 'interrogatoire'),
            array('speciality_name' => 'piratage'),
        );
        DB::table('specialities')->insert($specialities);


        // insert data into table  status
        DB::table('statuses')->delete();
        $status = array(
            array('status_name' => 'En preparation'),
            array('status_name' => 'Attribuée'),
            array('status_name' => 'En cour'),
            array('status_name' => 'Terminée'),

        );
        DB::table('statuses')->insert($status);

        // insert data into missionTypes table
        DB::table('mission_types')->delete();
        $status = array(
            array('type_name' => 'Assasinat'),
            array('type_name' => 'Recrutement'),
            array('type_name' => 'Enlèvement'),
            array('type_name' => 'Ecoute'),

        );
        DB::table('mission_types')->insert($status);

        DB::table('safe_houses_type')->delete();
        $status = array(
            array('safe_house_type' => 'Sécurisé'),
            array('safe_house_type' => 'Observation'),
        );
        DB::table('safe_houses_type')->insert($status);



        User::factory(10)->create();
        Agent::factory(25)->create();
        Contact::factory(100)->create();
        Target::factory(100)->create();

        //TODO: find how automatise this array
         //insert data into agentspecialities
        DB::table('agent_specialities')->delete();
        $status =array(
            array('agent_id' => 1,'speciality_id'=>5),
            array('agent_id' => 1,'speciality_id'=>3),
            array('agent_id' => 1,'speciality_id'=>10),
            array('agent_id' => 2,'speciality_id'=>6),
            array('agent_id' => 2,'speciality_id'=>8),
            array('agent_id' => 3,'speciality_id'=>4),
            array('agent_id' => 3,'speciality_id'=>9),
            array('agent_id' => 4,'speciality_id'=>1),
            array('agent_id' => 5,'speciality_id'=>8),
            array('agent_id' => 6,'speciality_id'=>5),
            array('agent_id' => 6,'speciality_id'=>6),
            array('agent_id' => 6,'speciality_id'=>7),
            array('agent_id' => 7,'speciality_id'=>3),
            array('agent_id' => 7,'speciality_id'=>9),
            array('agent_id' => 8,'speciality_id'=>10),
            array('agent_id' => 9,'speciality_id'=>1),
            array('agent_id' => 10,'speciality_id'=>2),
            array('agent_id' => 10,'speciality_id'=>5),
            array('agent_id' => 10,'speciality_id'=>4),
            array('agent_id' => 11,'speciality_id'=>8),
            array('agent_id' => 12,'speciality_id'=>6),
            array('agent_id' => 12,'speciality_id'=>7),
            array('agent_id' => 13,'speciality_id'=>1),
            array('agent_id' => 13,'speciality_id'=>4),
            array('agent_id' => 14,'speciality_id'=>9),
            array('agent_id' => 14,'speciality_id'=>10),
            array('agent_id' => 15,'speciality_id'=>5),
            array('agent_id' => 15,'speciality_id'=>2),
            array('agent_id' => 15,'speciality_id'=>3),
            array('agent_id' => 16,'speciality_id'=>1),
            array('agent_id' => 17,'speciality_id'=>8),
            array('agent_id' => 17,'speciality_id'=>10),
            array('agent_id' => 17,'speciality_id'=>3),
            array('agent_id' => 18,'speciality_id'=>2),
            array('agent_id' => 18,'speciality_id'=>6),
            array('agent_id' => 19,'speciality_id'=>9),
            array('agent_id' => 19,'speciality_id'=>3),
            array('agent_id' => 20,'speciality_id'=>1),
            array('agent_id' => 20,'speciality_id'=>3),
            array('agent_id' => 20,'speciality_id'=>5),
            array('agent_id' => 21,'speciality_id'=>2),
            array('agent_id' => 21,'speciality_id'=>4),
            array('agent_id' => 21,'speciality_id'=>6),
            array('agent_id' => 22,'speciality_id'=>9),
            array('agent_id' => 22,'speciality_id'=>10),
            array('agent_id' => 23,'speciality_id'=>6),
            array('agent_id' => 23,'speciality_id'=>2),
            array('agent_id' => 23,'speciality_id'=>5),
            array('agent_id' => 24,'speciality_id'=>1),
            array('agent_id' => 24,'speciality_id'=>3),
            array('agent_id' => 25,'speciality_id'=>1),
        );
        DB::table('agent_specialities')->insert($status);

        Mission::factory(800)->create();
        SafeHouse::factory(50)->create();
        $this->call([
                        AgentMissions::class,
                        TargetMissions::class,
                        ContactMissions::class,
                        SafeHouseMissions::class]);
    }
}
